### PR TITLE
C# tests

### PR DESCRIPTION
**Pull request by bstaletic**
Quoting gitter:

> If `Diagnostics_ZeroBasedLineAndColumn_test` or `Diagnostics_Basic_test` are run before `GetCompletions_DefaultToIdentifier_test` and `GetCompletions_Basic_test`, the latter two fail.

Once again, renaming `get_completions_test.py` to `1_get_completions_test.py` does help. I'm out of ideas...

---
This change is [Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/25)

### CODE REVIEW

**Review by puremourning — CHANGES_REQUESTED** [review]
nice one thanks!

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/25#-:-MAW_lnLDjOgIaXoqMpo:brrjwcg)* status: all files reviewed, 2 unresolved discussions (waiting on @bstaletic)

___
*[ycmd/completers/cs/cs_completer.py, line 47 at r1](https://reviewable.io/reviews/puremourning/ycmd-1/25#-MAWZdo859_wjFUpycPX:-MAWZdo859_wjFUpycPY:b-jfjqp1) ([raw file](https://github.com/puremourning/ycmd-1/blob/2a8ac37cbddf515efe6b42a456f249da95b2b330/ycmd/completers/cs/cs_completer.py#L47)):*
> ```Python
> )
> PATH_TO_OMNISHARP_ROSLYN_BINARY = os.path.join(
>   PATH_TO_ROSLYN_OMNISHARP, 'Omnisharp.exe' )
> ```

confused what this is here for? If the next 2 lines are setting it to omnishaprt/OmniSharp.exe, is this path just wrong, or are the layouts different on windows/unix ?
___
*[ycmd/completers/cs/cs_completer.py, line 87 at r1](https://reviewable.io/reviews/puremourning/ycmd-1/25#-MAW_OGbC0EEQk41NrpO:-MAW_OGc1l8QOSWIcd8S:bl7ruvk) ([raw file](https://github.com/puremourning/ycmd-1/blob/2a8ac37cbddf515efe6b42a456f249da95b2b330/ycmd/completers/cs/cs_completer.py#L87)):*
> ```Python
>     self._solution_state_lock = threading.Lock()
>     self.SetSignatureHelpTriggers( [ '(', ',' ] )
>     if os.path.isfile( user_options[ 'roslyn_binary_path' ] ):
> ```

the check here is different from ShouldEnableCsCompleter. seems wrong. (p.s. i hate that we have this code duplicated)

**Review by bstaletic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/25)* status: all files reviewed, 2 unresolved discussions (waiting on @puremourning)

___
*[ycmd/completers/cs/cs_completer.py, line 47 at r1](https://reviewable.io/reviews/puremourning/ycmd-1/25#-MAWZdo859_wjFUpycPX:-MAWkAqbCc3fCaSz8zDK:bgh5vox) ([raw file](https://github.com/puremourning/ycmd-1/blob/2a8ac37cbddf515efe6b42a456f249da95b2b330/ycmd/completers/cs/cs_completer.py#L47)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

confused what this is here for? If the next 2 lines are setting it to omnishaprt/OmniSharp.exe, is this path just wrong, or are the layouts different on windows/unix ?
</blockquote></details>

Different layouts.
___
*[ycmd/completers/cs/cs_completer.py, line 87 at r1](https://reviewable.io/reviews/puremourning/ycmd-1/25#-MAW_OGbC0EEQk41NrpO:-MAWkM4_0amdrwNtN9-c:b7kt70t) ([raw file](https://github.com/puremourning/ycmd-1/blob/2a8ac37cbddf515efe6b42a456f249da95b2b330/ycmd/completers/cs/cs_completer.py#L87)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

the check here is different from ShouldEnableCsCompleter. seems wrong. (p.s. i hate that we have this code duplicated)
</blockquote></details>

If we got to `__init__()` we know that either `os.path.isfile( ... )` is true and the user has set the variable explicitly (empty string as the default value would be false) or we should fall back to the `OmniSharp.exe` in `third_party`.

The only case where this differs from the `ShouldEnableCsCompleter()` is in

```python
  if user_roslyn_path and not os.path.isfile( user_roslyn_path ):
    LOGGER.error( 'No omnisharp-roslyn executable at %s', user_roslyn_path )
    # We should trust the user who specifically asked for a custom path.
    return False
```

If that was the case, we wouldn't have entered `__init__()`.

**Review by puremourning — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/25)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[ycmd/completers/cs/cs_completer.py, line 87 at r1](https://reviewable.io/reviews/puremourning/ycmd-1/25#-MAW_OGbC0EEQk41NrpO:-MAWnyCNAzylyoUGYUs4:b3585on) ([raw file](https://github.com/puremourning/ycmd-1/blob/2a8ac37cbddf515efe6b42a456f249da95b2b330/ycmd/completers/cs/cs_completer.py#L87)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

If we got to `__init__()` we know that either `os.path.isfile( ... )` is true and the user has set the variable explicitly (empty string as the default value would be false) or we should fall back to the `OmniSharp.exe` in `third_party`.

The only case where this differs from the `ShouldEnableCsCompleter()` is in

```python
  if user_roslyn_path and not os.path.isfile( user_roslyn_path ):
    LOGGER.error( 'No omnisharp-roslyn executable at %s', user_roslyn_path )
    # We should trust the user who specifically asked for a custom path.
    return False
```

If that was the case, we wouldn't have entered `__init__()`.
</blockquote></details>

eh, ok. not a fan of the duplication or the implicit interplay between them, but i don't feel that strongly about it.

**Review by bstaletic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/25)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[ycmd/completers/cs/cs_completer.py, line 87 at r1](https://reviewable.io/reviews/puremourning/ycmd-1/25#-MAW_OGbC0EEQk41NrpO:-MAWpyAoCnvpW9yBKzrN:b-d82ywj) ([raw file](https://github.com/puremourning/ycmd-1/blob/2a8ac37cbddf515efe6b42a456f249da95b2b330/ycmd/completers/cs/cs_completer.py#L87)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

eh, ok. not a fan of the duplication or the implicit interplay between them, but i don't feel that strongly about it.
</blockquote></details>

Do you want to pull the logic out of `ShouldEnable` functions to solve duplication?

**Review by puremourning — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/25)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[ycmd/completers/cs/cs_completer.py, line 87 at r1](https://reviewable.io/reviews/puremourning/ycmd-1/25#-MAW_OGbC0EEQk41NrpO:-MAWrLmt-a9XCzV6F2Mt:b-koin73) ([raw file](https://github.com/puremourning/ycmd-1/blob/2a8ac37cbddf515efe6b42a456f249da95b2b330/ycmd/completers/cs/cs_completer.py#L87)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

Do you want to pull the logic out of `ShouldEnable` functions to solve duplication?
</blockquote></details>

nah it's fine. unless you're bored.

Seems that the CI is red on this commit though...

**Comment by bstaletic** [comment]
We can close this.

**Pull request closed without merging**
