### PR TITLE
test

### PR DESCRIPTION
**Pull request by bstaletic**
test

---
This change is [Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/15)

### CODE REVIEW

**Comment by puremourning** [comment]
Could you force-push or re-open ? Trying to get azure to trigger

**Comment by bstaletic** [comment]
Pushed.

**Comment by puremourning** [comment]
Woop thanks. looks like it is going

**Review by puremourning — APPROVED** [review]
tanks

**Comment by puremourning** [comment]
I expect the build to fail, because my fork is a mess of random changes that don't pass the tests, but I'll use the check summary to see that it identified the all of the conditions correctly.

**Comment by puremourning** [comment]
Yep looks good.

**Pull request closed without merging**
