### PR TITLE
[READY] Fix TypeScript unicode tests on Windows

### PR DESCRIPTION
**Pull request by micbou**
See the commit message for the details.

To be fair, it should have be done this way in the first place.

---

This change is [Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/1)

### CODE REVIEW

**Comment by puremourning** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[ycmd/completers/typescript/typescript_completer.py, line 197 [r1]](https://reviewable.io:443/reviews/puremourning/ycmd-1/1#-KFiVlx4EaRFnK397yUW:-KFiVlx5kBZ68HMItLh3:434612629) ([raw file](https://github.com/puremourning/ycmd-1/blob/516cab519055a56add3ad39b6afcfd66ae07630d/ycmd/completers/typescript/typescript_completer.py#L197)):_
One problem we have is that we have no control over the TSServer version (we don't ship it as a submodule). Would it be possible to, say:
- read 'Content-length' bytes
- if on windows, and the last char is `\r`, read an extra byte

Does that solve it in the case of both broken and fixed tsserver?

Actually, right now, we just don't care, because that bug is still not fixed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/puremourning/ycmd-1/1)_

**Comment by puremourning** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/puremourning/ycmd-1/1)_

**Comment by puremourning** [comment]
Thanks!!

**Comment by micbou** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[ycmd/completers/typescript/typescript_completer.py, line 197 [r1]](https://reviewable.io:443/reviews/puremourning/ycmd-1/1#-KFiVlx4EaRFnK397yUW:-KFiiMnp9AT4juvvwh6E:-708031751) ([raw file](https://github.com/puremourning/ycmd-1/blob/516cab519055a56add3ad39b6afcfd66ae07630d/ycmd/completers/typescript/typescript_completer.py#L197)):_
I didn't think of that. Something like:

``` python
content = self._tsserver_handle.stdout.readline( contentlength )
if utils.OnWindows() and content.endswith( b'\r' ):
   content += self._tsserver_handle.stdout.read( 1 )
```

does the job. You can amend my commit if you want (and remove the TODO).

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/puremourning/ycmd-1/1)_

**Pull request merged**
