### PR TITLE
Tests for GetType, GetDoc and GoToReferences

### PR DESCRIPTION
**Pull request by bstaletic**
Formating is probably off here and there. I rechecked, but I probably mised something.

### CODE REVIEW

**Review by puremourning — APPROVED** [review]
Thanks so much!

**Comment by puremourning** [comment]
There are a few flake8 niggles, but I will fix them up.

**Comment by bstaletic** [comment]
I already have the patch. Are you sure you don't want me to send another PR.

**Comment by puremourning** [comment]
Up to you. I wanted to run the tests, so I've done it.

Though, I do get failures:

```

======================================================================
FAIL: ycmd.tests.java.subcommands_test.Subcommands_GoToReferences_test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ben/.pyenv/versions/ycmd-system/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/tests/java/__init__.py", line 83, in Wrapper
    return test( shared_app, *args, **kwargs )
  File "/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/tests/java/subcommands_test.py", line 356, in Subcommands_GoToReferences_test
    'line_num': 8
AssertionError: [{u'line_num': 28, u'column_num': 9, u'filepath': u'/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/tests/java/testdata/simple_eclipse_project/src/com/test/TestFactory.java'}, {u'line_num': 8, u'column_num': 7, u'filepath': u'/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/tests/java/testdata/simple_eclipse_project/src/com/test/TestLauncher.java'}] != [{u'line_num': 23, u'column_num': 9, u'filepath': u'/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/tests/java/testdata/simple_eclipse_project/src/com/test/TestFactory.java'}, {u'line_num': 8, u'column_num': 7, u'filepath': u'/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/tests/java/testdata/simple_eclipse_project/src/com/test/TestLauncher.java'}]
-------------------- >> begin captured logging << --------------------
ycmd.handlers: INFO: Received command request
ycmd.completers.language_server.language_server_completer: DEBUG: TX: Sending message b'Content-Length: 336
Content-Type: application/vscode-jsonrpc;charset=utf8

{"id": "43", "jsonrpc": "2.0", "method": "textDocument/references", "params": {"context": {"includeDeclaration": true}, "position": {"character": 14, "line": 9}, "textDocument": {"uri": "file:///Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/tests/java/testdata/simple_eclipse_project/src/com/test/AbstractTestWidget.java"}}}'
ycmd.completers.language_server.language_server_completer: DEBUG: RX: Received message: {u'params': {u'message': u'11-Sep-2017 02:16:58 >> document/references', u'type': 3}, u'jsonrpc': u'2.0', u'method': u'window/logMessage'}
ycmd.completers.language_server.language_server_completer: DEBUG: RX: Received message: {u'jsonrpc': u'2.0', u'id': u'43', u'result': [{u'range': {u'start': {u'line': 27, u'character': 8}, u'end': {u'line': 27, u'character': 34}}, u'uri': u'file:///Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/tests/java/testdata/simple_eclipse_project/src/com/test/TestFactory.java'}, {u'range': {u'start': {u'line': 7, u'character': 6}, u'end': {u'line': 7, u'character': 32}}, u'uri': u'file:///Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/tests/java/testdata/simple_eclipse_project/src/com/test/TestLauncher.java'}]}
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: ycmd.tests.java.subcommands_test.Subcommands_RefactorRename_MultipleFiles_test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ben/.pyenv/versions/ycmd-system/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/tests/java/__init__.py", line 83, in Wrapper
    return test( shared_app, *args, **kwargs )
  File "/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/tests/java/subcommands_test.py", line 449, in Subcommands_RefactorRename_MultipleFiles_test
    'location': LocationMatcher( filepath3, 8, 7 )
  File "/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/tests/java/subcommands_test.py", line 94, in RunTest
    assert_that( response.json, test[ 'expect' ][ 'data' ] )
AssertionError:
Expected: a dictionary containing {'fixits': a sequence containing [a dictionary containing {'chunks': a sequence containing [a dictionary containing {'range': a dictionary containing {'end': a dictionary containing {'column_num': <39>, 'filepath': '/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/tests/java/testdata/simple_eclipse_project/src/com/test/AbstractTestWidget.java', 'line_num': <10>}, 'start': a dictionary containing {'column_num': <15>, 'filepath': '/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/tests/java/testdata/simple_eclipse_project/src/com/test/AbstractTestWidget.java', 'line_num': <10>}}, 'replacement_text': 'a-quite-long-string'}, a dictionary containing {'range': a dictionary containing {'end': a dictionary containing {'column_num': <33>, 'filepath': '/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/tests/java/testdata/simple_eclipse_project/src/com/test/TestFactory.java', 'line_num': <23>}, 'start': a dictionary containing {'column_num': <9>, 'filepath': '/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/tests/java/testdata/simple_eclipse_project/src/com/test/TestFactory.java', 'line_num': <23>}}, 'replacement_text': 'a-quite-long-string'}, a dictionary containing {'range': a dictionary containing {'end': a dictionary containing {'column_num': <39>, 'filepath': '/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/tests/java/testdata/simple_eclipse_project/src/com/test/TestWidgetImpl.java', 'line_num': <20>}, 'start': a dictionary containing {'column_num': <15>, 'filepath': '/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/tests/java/testdata/simple_eclipse_project/src/com/test/TestWidgetImpl.java', 'line_num': <20>}}, 'replacement_text': 'a-quite-long-string'}, a dictionary containing {'range': a dictionary containing {'end': a dictionary containing {'column_num': <31>, 'filepath': '/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/tests/java/testdata/simple_eclipse_project/src/com/test/TestLauncher.java', 'line_num': <8>}, 'start': a dictionary containing {'column_num': <7>, 'filepath': '/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/tests/java/testdata/simple_eclipse_project/src/com/test/TestLauncher.java', 'line_num': <8>}}, 'replacement_text': 'a-quite-long-string'}], 'location': a dictionary containing {'column_num': <7>, 'filepath': '/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/tests/java/testdata/simple_eclipse_project/src/com/test/TestLauncher.java', 'line_num': <8>}}]}
     but: value for 'fixits' item 0: value for 'chunks' item 1: value for 'range' value for 'end' value for 'line_num' was <28>

-------------------- >> begin captured stdout << ---------------------
completer response: {u'fixits': [{u'chunks': [{u'range': {u'end': {u'column_num': 39,
                                               u'filepath': u'/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/tests/java/testdata/simple_eclipse_project/src/com/test/AbstractTestWidget.java',
                                               u'line_num': 10},
                                      u'start': {u'column_num': 15,
                                                 u'filepath': u'/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/tests/java/testdata/simple_eclipse_project/src/com/test/AbstractTestWidget.java',
                                                 u'line_num': 10}},
                           u'replacement_text': u'a-quite-long-string'},
                          {u'range': {u'end': {u'column_num': 33,
                                               u'filepath': u'/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/tests/java/testdata/simple_eclipse_project/src/com/test/TestFactory.java',
                                               u'line_num': 28},
                                      u'start': {u'column_num': 9,
                                                 u'filepath': u'/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/tests/java/testdata/simple_eclipse_project/src/com/test/TestFactory.java',
                                                 u'line_num': 28}},
                           u'replacement_text': u'a-quite-long-string'},
                          {u'range': {u'end': {u'column_num': 39,
                                               u'filepath': u'/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/tests/java/testdata/simple_eclipse_project/src/com/test/TestWidgetImpl.java',
                                               u'line_num': 20},
                                      u'start': {u'column_num': 15,
                                                 u'filepath': u'/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/tests/java/testdata/simple_eclipse_project/src/com/test/TestWidgetImpl.java',
                                                 u'line_num': 20}},
                           u'replacement_text': u'a-quite-long-string'},
                          {u'range': {u'end': {u'column_num': 31,
                                               u'filepath': u'/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/tests/java/testdata/simple_eclipse_project/src/com/test/TestLauncher.java',
                                               u'line_num': 8},
                                      u'start': {u'column_num': 7,
                                                 u'filepath': u'/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/tests/java/testdata/simple_eclipse_project/src/com/test/TestLauncher.java',
                                                 u'line_num': 8}},
                           u'replacement_text': u'a-quite-long-string'}],
              u'location': {u'column_num': 7,
                            u'filepath': u'/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/tests/java/testdata/simple_eclipse_project/src/com/test/TestLauncher.java',
                            u'line_num': 8},
              u'text': u''}]}

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
ycmd.completers.language_server.language_server_completer: DEBUG: RX: Received message: {u'params': {u'message': u'11-Sep-2017 02:16:58 >> document/didClose', u'type': 3}, u'jsonrpc': u'2.0', u'method': u'window/logMessage'}
ycmd.completers.language_server.language_server_completer: DEBUG: RX: Received message: {u'params': {u'message': u'11-Sep-2017 02:16:58 Releasing AST for /Test/src/com/test/TestFactory.java', u'type': 3}, u'jsonrpc': u'2.0', u'method': u'window/logMessage'}
ycmd.handlers: INFO: Received event notification
ycmd.handlers: DEBUG: Event name: FileReadyToParse
ycmd.completers.all.identifier_completer: INFO: Adding buffer identifiers for file: /Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/tests/java/testdata/simple_eclipse_project/src/com/test/TestLauncher.java
ycmd.completers.language_server.language_server_completer: DEBUG: TX: Sending Notification b'Content-Length: 689
Content-Type: application/vscode-jsonrpc;charset=utf8

{"jsonrpc": "2.0", "method": "textDocument/didOpen", "params": {"textDocument": {"languageId": "java", "text": "package com.test;\n\nclass TestLauncher {\n  private TestFactory factory = new TestFactory();\n\n  private void Run() {\n    AbstractTestWidget w = factory.getWidget( \"Test\" );\n    w.doSomethingVaguelyUseful();\n\n    System.out.println( \"Did something useful: \" + w.getWidgetInfo() );\n  }\n\n  public static void main( String[] args ) {\n    TestLauncher l = new TestLauncher();\n    l.Run();\n  }\n}\n", "uri": "file:///Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/tests/java/testdata/simple_eclipse_project/src/com/test/TestLauncher.java", "version": 2}}}'
ycmd.handlers: INFO: Received command request
ycmd.completers.language_server.language_server_completer: DEBUG: TX: Sending message b'Content-Length: 318
Content-Type: application/vscode-jsonrpc;charset=utf8

{"id": "44", "jsonrpc": "2.0", "method": "textDocument/rename", "params": {"newName": "a-quite-long-string", "position": {"character": 6, "line": 7}, "textDocument": {"uri": "file:///Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/tests/java/testdata/simple_eclipse_project/src/com/test/TestLauncher.java"}}}'
ycmd.completers.language_server.language_server_completer: DEBUG: RX: Received message: {u'params': {u'message': u'11-Sep-2017 02:16:58 >> document/didOpen', u'type': 3}, u'jsonrpc': u'2.0', u'method': u'window/logMessage'}
ycmd.completers.language_server.language_server_completer: DEBUG: RX: Received message: {u'params': {u'message': u'11-Sep-2017 02:16:58 >> document/rename', u'type': 3}, u'jsonrpc': u'2.0', u'method': u'window/logMessage'}
ycmd.completers.language_server.language_server_completer: DEBUG: RX: Received message: {u'jsonrpc': u'2.0', u'id': u'44', u'result': {u'changes': {u'file:///Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/tests/java/testdata/simple_eclipse_project/src/com/test/AbstractTestWidget.java': [{u'newText': u'a-quite-long-string', u'range': {u'start': {u'line': 9, u'character': 14}, u'end': {u'line': 9, u'character': 38}}}], u'file:///Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/tests/java/testdata/simple_eclipse_project/src/com/test/TestFactory.java': [{u'newText': u'a-quite-long-string', u'range': {u'start': {u'line': 27, u'character': 8}, u'end': {u'line': 27, u'character': 32}}}], u'file:///Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/tests/java/testdata/simple_eclipse_project/src/com/test/TestWidgetImpl.java': [{u'newText': u'a-quite-long-string', u'range': {u'start': {u'line': 19, u'character': 14}, u'end': {u'line': 19, u'character': 38}}}], u'file:///Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/tests/java/testdata/simple_eclipse_project/src/com/test/TestLauncher.java': [{u'newText': u'a-quite-long-string', u'range': {u'start': {u'line': 7, u'character': 6}, u'end': {u'line': 7, u'character': 30}}}]}}}
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 937 tests in 120.248s

FAILED (SKIP=20, failures=2)
Traceback (most recent call last):
  File "./run_tests.py", line 236, in <module>
    Main()
  File "./run_tests.py", line 232, in Main
    NoseTests( parsed_args, nosetests_args )
  File "./run_tests.py", line 220, in NoseTests
    '-m', 'nose.__main__' ] + nosetests_args )
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/ben/.pyenv/versions/ycmd-system/bin/python', u'-m', u'nose.__main__', u'-v', u'--with-id', u'/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd']' returned non-zero exit status 1

```

**Comment by bstaletic** [comment]
I don't know what or how it happened. I'll fix it right away.

Sorry about that.

**Comment by puremourning** [comment]
No sweat :)

**Comment by bstaletic** [comment]
Hmmm... If the tests are run in just the right order they all pass. I'll have to debug a bit longer.

**Comment by puremourning** [comment]
No worries. Take your time. No rush at all.

**Comment by bstaletic** [comment]
This is just before fixing the flake8 and **rebasing**.

```
bstaletic@gentoo ycmd  (git)-[java-language-server]-% ./run_tests.py --skip-build ycmd.tests.java.debug_info_test --no-flake8                                    -- INSERT --
Running tests on Python 2.7.13
#10 ycmd.tests.java.debug_info_test.DebugInfo_test ... ok

----------------------------------------------------------------------
Ran 1 test in 3.841s

OK
bstaletic@gentoo ycmd  (git)-[java-language-server]-% ./run_tests.py --skip-build ycmd.tests.java.subcommands_test --no-flake8                                   -- INSERT --
Running tests on Python 2.7.13
#16 ycmd.tests.java.subcommands_test.Subcommands_DefinedSubcommands_test ... ok
#2 ycmd.tests.java.subcommands_test.Subcommands_GetDoc_Class_test ... ok
#3 ycmd.tests.java.subcommands_test.Subcommands_GetDoc_Method_test ... ok
#4 ycmd.tests.java.subcommands_test.Subcommands_GetType_ClassMemberVariable_test ... ok
#5 ycmd.tests.java.subcommands_test.Subcommands_GetType_Class_test ... ok
#6 ycmd.tests.java.subcommands_test.Subcommands_GetType_Constructor_test ... ok
#7 ycmd.tests.java.subcommands_test.Subcommands_GetType_MethodArgument_test ... ok
#8 ycmd.tests.java.subcommands_test.Subcommands_GetType_MethodVariable_test ... ok
#9 ycmd.tests.java.subcommands_test.Subcommands_GetType_Method_test ... ok
#15 ycmd.tests.java.subcommands_test.Subcommands_GoToReferences_test ... ok
#18 ycmd.tests.java.subcommands_test.Subcommands_RefactorRename_Missing_New_Name_test ... ok
#19 ycmd.tests.java.subcommands_test.Subcommands_RefactorRename_MultipleFiles_test ... ok
#17 ycmd.tests.java.subcommands_test.Subcommands_RefactorRename_Simple_test ... ok

----------------------------------------------------------------------
Ran 13 tests in 8.655s

OK
```

**Comment by bstaletic** [comment]
Ha! `10643db2` commit broke the tests. I'll fix them tomorrow.

**Pull request merged**
