### PR TITLE
Fix tests after rebase

### PR DESCRIPTION
**Pull request by bstaletic**
This is what made the tests fail.

EDIT: This time I checked flake8 too.

### CODE REVIEW

**Comment by bstaletic** [comment]
That should fix the tests, but if we need not care about the order of chunks for `RefactorRename` a mess up like this wouldn't have happened.

**Comment by bstaletic** [comment]
```
#11 ycmd.tests.java.subcommands_test.Subcommands_RefactorRename_Missing_New_Name_test ... ok
#12 ycmd.tests.java.subcommands_test.Subcommands_RefactorRename_MultipleFiles_test ... ok
#13 ycmd.tests.java.subcommands_test.Subcommands_RefactorRename_Simple_test ... ok
```

As you can see, on my machine these tests are passing. On other machines they are failing because the order of chunks is different.

**Comment by puremourning** [comment]
Hmm. The sequence of chunks is important. As we discussed, jdtls seems to require they are applied in a particular sequence. If the sequence isn't stable, i'm not sure what hope we have.

Thanks again for this. I will see if i can understand why it changed and why it is inconsistent.

**Comment by bstaletic** [comment]
Not only did it change once, but I already changed it a few times before this one.

On September 11, 2017 1:00:11 PM GMT+02:00, Ben Jackson <notifications@github.com> wrote:
>Hmm. The sequence of chunks is important. As we discussed, jdtls seems
>to require they are applied in a particular sequence. If the sequence
>isn't stable, i'm not sure what hope we have.
>
>Thanks again for this. I will see if i can understand why it changed
>and why it is inconsistent.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/puremourning/ycmd-1/pull/8#issuecomment-328495714

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by puremourning** [comment]
I understand the problem. I've fixed it. And MERGED!

Thanks again!

 Ben Jackson @puremourning 12:07
oh i get it
https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#workspaceedit
changes is an object
(dictionary)
so the chunks are file-wise order independent
which is OK, cos YCM client applies exactly that
but the response might have files in funny sequence

micbou @micbou 12:09
How would you order files?
by name?

Ben Jackson @puremourning 12:09
i'll just sort them
yeah, that's what YCM client does
it's for the tests - Boris' tests are failing cos the chunks are out of order
but the sequence of chunks (wihtin a file) is important
so i'll just sort the file names, so the sequence is stable
then the tests will pass
and there will be much rejoicing.

micbou @micbou 12:10
why not using contains_inanyorder?

Ben Jackson @puremourning 12:11
again, because the sequence (within a file) is strictly important
and the ycmd api doesn't separate chunks by file
it's just one list

micbou @micbou

**Comment by puremourning** [comment]
Where's the "much rejoicing" emoji ?

**Pull request merged**
