### PR TITLE
Update API documentation

### PR DESCRIPTION
**Pull request by micbou**
See https://micbou.github.io/ycmd/ for the result.

---
This change is [Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/13)

### CODE REVIEW

**Comment by micbou** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[api/swagger.yaml, line 55 at r1](https://reviewable.io:443/reviews/puremourning/ycmd-1/13#-L1SyqX-peY7FoovK1eP:-L1SyqX0wGubFPSGt0Z6:bpq9mnn) ([raw file](https://github.com/puremourning/ycmd-1/blob/e7af8cd85b94122dabd9a9bfb99cfbc92eebaa0d/api/swagger.yaml#L55)):*
> ```YAML
>     The ycmd server is typically started by a client in order to provide
>     services to it. Briefly, starting the server requires supplying some
>     configuration and initializing and security features (HMAC).
> ```

The two `and`s are awkward. Should the first one be replaced with a comma?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/puremourning/ycmd-1/13)*

**Comment by puremourning** [comment]
Thanks so much

just one tiny comment

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[api/swagger.yaml, line 55 at r1](https://reviewable.io:443/reviews/puremourning/ycmd-1/13#-L1SyqX-peY7FoovK1eP:-L1T1tvrJgj37g9Nq8DK:b-t58ve0) ([raw file](https://github.com/puremourning/ycmd-1/blob/e7af8cd85b94122dabd9a9bfb99cfbc92eebaa0d/api/swagger.yaml#L55)):*
<details><summary><i>Previously, micbou wrote…</i></summary><blockquote>

The two `and`s are awkward. Should the first one be replaced with a comma?
</blockquote></details>

i think the second one is just superfluous...
"supplying some configuration and initializing some security features"

---

*[api/swagger.yaml, line 1111 at r1](https://reviewable.io:443/reviews/puremourning/ycmd-1/13#-L1T3eaF3fc_iV1KVL9S:-L1T3eaF3fc_iV1KVL9T:b-r8a2f7) ([raw file](https://github.com/puremourning/ycmd-1/blob/e7af8cd85b94122dabd9a9bfb99cfbc92eebaa0d/api/swagger.yaml#L1111)):*
> ```YAML
>               completer:
>                 description: |-
>                   Contain debugging information on the completer for the given
> ```

Contain -> Contains

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/puremourning/ycmd-1/13#-:-L1T3r9I5lIwb8PUWyI_:b-2gb28i)*

**Comment by puremourning** [comment]
Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/puremourning/ycmd-1/13)*

**Comment by micbou** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[api/swagger.yaml, line 55 at r1](https://reviewable.io:443/reviews/puremourning/ycmd-1/13#-L1SyqX-peY7FoovK1eP:-L1T4Vg_WF_Zp7COXmP8:b-896fix) ([raw file](https://github.com/puremourning/ycmd-1/blob/e7af8cd85b94122dabd9a9bfb99cfbc92eebaa0d/api/swagger.yaml#L55)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

i think the second one is just superfluous...
"supplying some configuration and initializing some security features"
</blockquote></details>

Done.

---

*[api/swagger.yaml, line 1111 at r1](https://reviewable.io:443/reviews/puremourning/ycmd-1/13#-L1T3eaF3fc_iV1KVL9S:-L1T4YuPsj9jA66TkPSo:b-896fix) ([raw file](https://github.com/puremourning/ycmd-1/blob/e7af8cd85b94122dabd9a9bfb99cfbc92eebaa0d/api/swagger.yaml#L1111)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

Contain -> Contains
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/puremourning/ycmd-1/13)*

**Comment by puremourning** [comment]
Thanks!

**Pull request merged**
