### PR TITLE
[READY] Use offsets instead of names for parameters

### PR DESCRIPTION
**Pull request by bstaletic**
Instead of sending parameters as strings, we send them as a list of integers to denote the `[begin, end)` range of the parameter.

---
This change is [Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/20)

### CODE REVIEW

**Review by puremourning — CHANGES_REQUESTED** [review]
Thanks, NOICE

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/20#-:-LqumXCnCM0iePaBoRPa:bnr6wbs)* status: all files reviewed, 2 unresolved discussions (waiting on @bstaletic)

___
*[docs/openapi.yml, line 1028 at r1](https://reviewable.io/reviews/puremourning/ycmd-1/20#-LqukDlyC1zyZl4zihEz:-LqukDlyC1zyZl4zihF-:bxrsov1) ([raw file](https://github.com/puremourning/ycmd-1/blob/40553fe219789b7d855cb47f04691e04cdb41271/docs/openapi.yml#L1028)):*
> ```YAML
>                                  containing signature label.
>                                type: array
>                                items:
> ```

i think there's a constraint we can add that there are only 2 entries. Though i think i would prefer to use an object with 'start' and 'end' or 'start' and 'end' positions. 

I considered start+length, but that's bad due to unicode. Speaking of unicode... Normally our position parameters are byte offsets. it seems from the implementation that in this case they are 'character' (ish... we'd describe them as codepoint) offsets within the string `label`. I'm not sure how i feel about this, but i'm leaning towards saying that we should be using byte offsets for these parameters, and those require a bit of shenanigans when we create the responses.

note to self: need to test unicode characters in signatures!
___
*[ycmd/completers/language_server/language_server_completer.py, line 1088 at r1](https://reviewable.io/reviews/puremourning/ycmd-1/20#-LqulN5659SmTe8fnLio:-LqulN5659SmTe8fnLip:b7c2bsc) ([raw file](https://github.com/puremourning/ycmd-1/blob/40553fe219789b7d855cb47f04691e04cdb41271/ycmd/completers/language_server/language_server_completer.py#L1088)):*
> ```Python
>       for arg in sig[ 'parameters' ]:
>         arg_label = arg[ 'label' ]
>         if not isinstance( arg_label, list ):
> ```

when is the label a list ?

**Review by bstaletic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/20)* status: all files reviewed, 2 unresolved discussions (waiting on @puremourning)

___
*[docs/openapi.yml, line 1028 at r1](https://reviewable.io/reviews/puremourning/ycmd-1/20#-LqukDlyC1zyZl4zihEz:-LqunH_w4p-8bV9kwYQg:b-7c6ev3) ([raw file](https://github.com/puremourning/ycmd-1/blob/40553fe219789b7d855cb47f04691e04cdb41271/docs/openapi.yml#L1028)):*
> i think there's a constraint we can add that there are only 2 entries. 

How can we specify that constraint? Just add to the description?

> Though i think i would prefer to use an object with 'start' and 'end' or 'start' and 'end' positions.

I thought about that too, but I decided against it because LSP specification says that a server may return `[begind_offset, end_offset]`, so this way we can just forward what LSP server gave us if a server decides to send offsets.

> Normally our position parameters are byte offsets. it seems from the implementation that in this case they are 'character' (ish... we'd describe them as codepoint) offsets within the string label. I'm not sure how i feel about this, but i'm leaning towards saying that we should be using byte offsets for these parameters, and those require a bit of shenanigans when we create the responses.

I didn't even think of that. This makes sense. Don't we have a `CodepointOffsetToByteOffset()` that we can use for this? I'm never certain when it comes to unicode.
___
*[ycmd/completers/language_server/language_server_completer.py, line 1088 at r1](https://reviewable.io/reviews/puremourning/ycmd-1/20#-LqulN5659SmTe8fnLio:-LquoCP--fkS7mL7bQTW:b-rmh9df) ([raw file](https://github.com/puremourning/ycmd-1/blob/40553fe219789b7d855cb47f04691e04cdb41271/ycmd/completers/language_server/language_server_completer.py#L1088)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

when is the label a list ?
</blockquote></details>

When LSP server decides that it is. I believe that's a new-ish edition of the protocol.

https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#textDocument_signatureHelp

**Review by puremourning — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/20)* status: all files reviewed, 2 unresolved discussions (waiting on @bstaletic and @puremourning)

___
*[docs/openapi.yml, line 1028 at r1](https://reviewable.io/reviews/puremourning/ycmd-1/20#-LqukDlyC1zyZl4zihEz:-LquxqIc1Urf0UMqDPcn:bxsj86n) ([raw file](https://github.com/puremourning/ycmd-1/blob/40553fe219789b7d855cb47f04691e04cdb41271/docs/openapi.yml#L1028)):*
Yeah, we have CodepointOffsetToByteOffset, which is what we want. you just pass it the original string, and the codepoint, and it tells you what that would be in bytes. neat.

> LSP specification says that a server may return [begind_offset, end_offset]

fair point. let's keep this way then.

> How can we specify that constraint? Just add to the description?

use `maxItems` https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.6.4.1

**Review by puremourning — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/20)* status: all files reviewed, 2 unresolved discussions (waiting on @bstaletic)

___
*[ycmd/completers/language_server/language_server_completer.py, line 1088 at r1](https://reviewable.io/reviews/puremourning/ycmd-1/20#-LqulN5659SmTe8fnLio:-LquyfUI1BXUI22pPfoU:bpantp6) ([raw file](https://github.com/puremourning/ycmd-1/blob/40553fe219789b7d855cb47f04691e04cdb41271/ycmd/completers/language_server/language_server_completer.py#L1088)):*
i thought that was the thing we opted out of

anyway if we were to support it, we actually have a little bit more work to do due to the UTF-16ness: 

> The offsets are based on a UTF-16 string representation as `Position` and `Range` does.

but we have helpers for that too. i think this is fine to leave, maybe with a comment that it's defensive ?

**Review by bstaletic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/20)* status: all files reviewed, 2 unresolved discussions (waiting on @bstaletic and @puremourning)

___
*[ycmd/completers/language_server/language_server_completer.py, line 1088 at r1](https://reviewable.io/reviews/puremourning/ycmd-1/20#-LqulN5659SmTe8fnLio:-LquzH3CAy17_ostjFq7:b-yo6kha) ([raw file](https://github.com/puremourning/ycmd-1/blob/40553fe219789b7d855cb47f04691e04cdb41271/ycmd/completers/language_server/language_server_completer.py#L1088)):*
> but we have helpers for that too. i think this is fine to leave, maybe with a comment that it's defensive ?

Silently wrong things seem scary. Maybe an `assert` would do better? `assert not isinstance( arg_label, list )`

**Review by bstaletic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/20)* status: 4 of 8 files reviewed, 2 unresolved discussions (waiting on @puremourning)

___
*[docs/openapi.yml, line 1028 at r1](https://reviewable.io/reviews/puremourning/ycmd-1/20#-LqukDlyC1zyZl4zihEz:-Lqv0bjt3sekGNCI1PQX:b-896fix) ([raw file](https://github.com/puremourning/ycmd-1/blob/40553fe219789b7d855cb47f04691e04cdb41271/docs/openapi.yml#L1028)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

Yeah, we have CodepointOffsetToByteOffset, which is what we want. you just pass it the original string, and the codepoint, and it tells you what that would be in bytes. neat.

> LSP specification says that a server may return [begind_offset, end_offset]

fair point. let's keep this way then.

> How can we specify that constraint? Just add to the description?

use `maxItems` https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.6.4.1

</blockquote></details>

Done.

**Review by puremourning — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/20)* status: all files reviewed, 2 unresolved discussions (waiting on @bstaletic)

___
*[ycmd/completers/language_server/language_server_completer.py, line 1088 at r1](https://reviewable.io/reviews/puremourning/ycmd-1/20#-LqulN5659SmTe8fnLio:-Lqv7eW-BJCppFcN9ZeG:b-96e7fw) ([raw file](https://github.com/puremourning/ycmd-1/blob/40553fe219789b7d855cb47f04691e04cdb41271/ycmd/completers/language_server/language_server_completer.py#L1088)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

> but we have helpers for that too. i think this is fine to leave, maybe with a comment that it's defensive ?

Silently wrong things seem scary. Maybe an `assert` would do better? `assert not isinstance( arg_label, list )`
</blockquote></details>

assert sounds good; this would bubble up to the user who would complain to us, who would complain to the server vendor (and probably relax the check)
___
*[ycmd/completers/language_server/language_server_completer.py, line 1095 at r2](https://reviewable.io/reviews/puremourning/ycmd-1/20#-Lqv7qEaDWimOox3yi53:-Lqv7qEaDWimOox3yi54:b-mp56ks) ([raw file](https://github.com/puremourning/ycmd-1/blob/e744dfd38e8c9786b533f2fd4086cc25e5446b07/ycmd/completers/language_server/language_server_completer.py#L1095)):*
> ```Python
>           end = utils.CodepointOffsetToByteOffset(
>                   sig_label,
>                   begin + len( arg_label ) )
> ```

i think begin is already a codepoint offset here, so this calculation is wrong

i think you should do the begin/end calculations as before, then use:

```
arg[ 'label' ] = [ utils.CodepointOffsetToByteOffset( sig_label, begin ), utils.CodepointOffsetToByteOffset( sig_label, end ) ]
```

**Review by bstaletic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/20)* status: all files reviewed, 2 unresolved discussions (waiting on @puremourning)

___
*[ycmd/completers/language_server/language_server_completer.py, line 1088 at r1](https://reviewable.io/reviews/puremourning/ycmd-1/20#-LqulN5659SmTe8fnLio:-LqvAAj69nf8hkPD-L3-:b-896fix) ([raw file](https://github.com/puremourning/ycmd-1/blob/40553fe219789b7d855cb47f04691e04cdb41271/ycmd/completers/language_server/language_server_completer.py#L1088)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

assert sounds good; this would bubble up to the user who would complain to us, who would complain to the server vendor (and probably relax the check)
</blockquote></details>

Done.
___
*[ycmd/completers/language_server/language_server_completer.py, line 1095 at r2](https://reviewable.io/reviews/puremourning/ycmd-1/20#-Lqv7qEaDWimOox3yi53:-Lqv92DUCaKCpclaHDew:b-54z2qz) ([raw file](https://github.com/puremourning/ycmd-1/blob/e744dfd38e8c9786b533f2fd4086cc25e5446b07/ycmd/completers/language_server/language_server_completer.py#L1095)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

i think begin is already a codepoint offset here, so this calculation is wrong

i think you should do the begin/end calculations as before, then use:

```
arg[ 'label' ] = [ utils.CodepointOffsetToByteOffset( sig_label, begin ), utils.CodepointOffsetToByteOffset( sig_label, end ) ]
```
</blockquote></details>

Absolutely right. Done.

**Review by puremourning — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/20#-:-LqvC9oeAIj4rp2lLjQJ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @puremourning)

**Comment by puremourning** [comment]
erm CI is busted

**Review by bstaletic — COMMENTED** [review]
CI has been fixed. I keep forgetting to pass the line to offset conversion function.

> *[Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/20#-:-LqvCfzs-N063dARsTJN:b5tuhbt)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @puremourning)

**Review by puremourning — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/20#-:-LqvD2xN3GrR7dZt9LkD:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @puremourning)

**Review by puremourning — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/20)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by puremourning** [comment]
Woo `\o/` thanks!

**Pull request merged**
