### PR TITLE
[RFC] Provide a way for clients to query if signature help is available

### PR DESCRIPTION
**Pull request by bstaletic**
RFC because, on gitter, you said that `/signature_help_available` is "a possibility", but didn't say why you don't like this approach.

If this is okay, I'll update the API docs and change the client side appropriately.

---
This change is [Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/19)

### CODE REVIEW

**Review by puremourning — CHANGES_REQUESTED** [review]
This is a lot simpler than i was expecting! nice .

Do you have prototype client code for this too ? I feel like it might be tricky for the client to know when to re-quesry this, but tbh it can do so fairly often (it's pretty cheap)

> *[Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/19#-:-LqvN8uUAENTQIifRktO:bp0ezhw)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @bstaletic)

___
*[ycmd/handlers.py, line 83 at r1](https://reviewable.io/reviews/puremourning/ycmd-1/19#-LqvN1ox3viEti2ylHaI:-LqvN1ox3viEti2ylHaJ:b541glb) ([raw file](https://github.com/puremourning/ycmd-1/blob/e0923e0065fa55af8f575959c23ce9a7846d9921/ycmd/handlers.py#L83)):*
> ```Python
>     completer = _server_state.GetFiletypeCompleter( [ filetype ] )
>     return _JsonResponse( completer.SignatureHelpAvailable() )
>   return _JsonResponse( False )
> ```

if subserver no supplied, raise exception rather than say no ?
___
*[ycmd/completers/language_server/language_server_completer.py, line 1070 at r1](https://reviewable.io/reviews/puremourning/ycmd-1/19#-LqvMBzVDVe37Lf-QlX_:-LqvMBzVDVe37Lf-QlXa:b-d5qw3j) ([raw file](https://github.com/puremourning/ycmd-1/blob/e0923e0065fa55af8f575959c23ce9a7846d9921/ycmd/completers/language_server/language_server_completer.py#L1070)):*
> ```Python
>     if not self.ServerIsReady():
>       return None
>     return bool( self._server_capabilities.get( 'signatureHelpProvider' ) )
> ```

`and not user_options[ 'disable_signature_help' ]` ?
___
*[ycmd/tests/clangd/signature_help_test.py, line 585 at r1](https://reviewable.io/reviews/puremourning/ycmd-1/19#-LqvMPNz-8Ww-6igoA17:-LqvMPNz-8Ww-6igoA18:bsy6o1q) ([raw file](https://github.com/puremourning/ycmd-1/blob/e0923e0065fa55af8f575959c23ce9a7846d9921/ycmd/tests/clangd/signature_help_test.py#L585)):*
> ```Python
>     response = app.get( '/signature_help_available',
>                         { 'subserver': 'cpp' } ).json
>     eq_( None, response )
> ```

what's a "None" in javascript ? Does it return `null` or something ?

Maybe we should return an object from the endpoint:

```
{
    'available': enum( YES, NO, PENDING )
}
```

?

**Review by puremourning — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/19)* status: all files reviewed, 3 unresolved discussions (waiting on @bstaletic)

**Review by bstaletic — COMMENTED** [review]
I don't have a prototype. I thought you might have some serious objections to this approach, so I wanted to wait.

There's a few options:

- Send it on every `OnFilreReadyToParse`.
- Send it before every `/signature_help` until we get a definitive answer.

In either case they should be separated, so that once we get the definitive answer, we can shut down the signature help timer. Any thoughts?

> *[Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/19#-:-LqvRDKLDS-QFoBVv_eh:bbhe3bx)* status: all files reviewed, 3 unresolved discussions (waiting on @puremourning)

___
*[ycmd/handlers.py, line 83 at r1](https://reviewable.io/reviews/puremourning/ycmd-1/19#-LqvN1ox3viEti2ylHaI:-LqvPnKu1FjOWfxQ6IqX:b-v7qy9k) ([raw file](https://github.com/puremourning/ycmd-1/blob/e0923e0065fa55af8f575959c23ce9a7846d9921/ycmd/handlers.py#L83)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

if subserver no supplied, raise exception rather than say no ?
</blockquote></details>

That's the thing I was completely uncertain about.

How do I actually raise an exception? We do have the `BuildExceptionResponse()`, but it is only used in POST requests and is returned in the `errors` property in `/completion` and `/signature_help`. Should I create a `BuildSignatureHelpAvailableResponse()`?
___
*[ycmd/completers/language_server/language_server_completer.py, line 1070 at r1](https://reviewable.io/reviews/puremourning/ycmd-1/19#-LqvMBzVDVe37Lf-QlX_:-LqvRRu95woJCP9rey8Y:b-896fix) ([raw file](https://github.com/puremourning/ycmd-1/blob/e0923e0065fa55af8f575959c23ce9a7846d9921/ycmd/completers/language_server/language_server_completer.py#L1070)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

`and not user_options[ 'disable_signature_help' ]` ?
</blockquote></details>

Done.
___
*[ycmd/tests/clangd/signature_help_test.py, line 585 at r1](https://reviewable.io/reviews/puremourning/ycmd-1/19#-LqvMPNz-8Ww-6igoA17:-LqvQ3B1Cr78lZNqDNst:b-yivhy6) ([raw file](https://github.com/puremourning/ycmd-1/blob/e0923e0065fa55af8f575959c23ce9a7846d9921/ycmd/tests/clangd/signature_help_test.py#L585)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

what's a "None" in javascript ? Does it return `null` or something ?

Maybe we should return an object from the endpoint:

```
{
    'available': enum( YES, NO, PENDING )
}
```

?
</blockquote></details>

None does end up as `null` when serialized.
I'm fine either way. Would the `YES`, `NO` and `PENDING` be strings?

**Review by bstaletic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/19)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @puremourning)

___
*[ycmd/handlers.py, line 83 at r1](https://reviewable.io/reviews/puremourning/ycmd-1/19#-LqvN1ox3viEti2ylHaI:-LqyqmRm28MDa0nGUxP9:b-896fix) ([raw file](https://github.com/puremourning/ycmd-1/blob/e0923e0065fa55af8f575959c23ce9a7846d9921/ycmd/handlers.py#L83)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

That's the thing I was completely uncertain about.

How do I actually raise an exception? We do have the `BuildExceptionResponse()`, but it is only used in POST requests and is returned in the `errors` property in `/completion` and `/signature_help`. Should I create a `BuildSignatureHelpAvailableResponse()`?
</blockquote></details>

Done.
___
*[ycmd/tests/clangd/signature_help_test.py, line 585 at r1](https://reviewable.io/reviews/puremourning/ycmd-1/19#-LqvMPNz-8Ww-6igoA17:-Lqyquy5Af630rohtjXq:b-896fix) ([raw file](https://github.com/puremourning/ycmd-1/blob/e0923e0065fa55af8f575959c23ce9a7846d9921/ycmd/tests/clangd/signature_help_test.py#L585)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

None does end up as `null` when serialized.
I'm fine either way. Would the `YES`, `NO` and `PENDING` be strings?
</blockquote></details>

Done.

**Review by puremourning — CHANGES_REQUESTED** [review]
thanks for doing this.

> Reviewed 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/19#-:-Lr-vRJk2Vv2GzR_WRTD:bkbzvr2)* status: all files reviewed, 5 unresolved discussions (waiting on @bstaletic)

___
*[docs/openapi.yml, line 923 at r2](https://reviewable.io/reviews/puremourning/ycmd-1/19#-Lr-u_Ky2RZ2wPl7wG_4:-Lr-u_Ky2RZ2wPl7wG_5:b-j7nek2) ([raw file](https://github.com/puremourning/ycmd-1/blob/2f29bd2cbbc6b990e5621390b761da088d9a6133/docs/openapi.yml#L923)):*
> ```YAML
>       parameters:
>         - name: subserver
>           in: body
> ```

are we really accepting it in the body, rather than on the query string ? I thought the GET requests used the query string 
___
*[docs/openapi.yml, line 926 at r2](https://reviewable.io/reviews/puremourning/ycmd-1/19#-Lr-uXcn3YH71IMrtrn1:-Lr-uXcn3YH71IMrtrn2:bmlsfvc) ([raw file](https://github.com/puremourning/ycmd-1/blob/2f29bd2cbbc6b990e5621390b761da088d9a6133/docs/openapi.yml#L926)):*
> ```
>             The context data, including the current cursor position, and details
>             of dirty buffers.
> ```

Not sure this is accurate
___
*[docs/openapi.yml, line 929 at r2](https://reviewable.io/reviews/puremourning/ycmd-1/19#-Lr-udaF5IBUdgLCyhBP:-Lr-udaF5IBUdgLCyhBQ:b-gjm012) ([raw file](https://github.com/puremourning/ycmd-1/blob/2f29bd2cbbc6b990e5621390b761da088d9a6133/docs/openapi.yml#L929)):*
> ```YAML
>           required: true
>           schema:
>             type: object
> ```

pretty sure it isn't an object with subserver key, but subserver query parameter (at least it _was_)
___
*[ycmd/completers/completer.py, line 443 at r2](https://reviewable.io/reviews/puremourning/ycmd-1/19#-Lr-urOX7hNOnj9pTL6X:-Lr-urOY7HQzuJq5I8Gy:b-kuea7n) ([raw file](https://github.com/puremourning/ycmd-1/blob/2f29bd2cbbc6b990e5621390b761da088d9a6133/ycmd/completers/completer.py#L443)):*
> ```Python
> 
>   def SignatureHelpAvailable( self ):
>     return 'NO'
> ```

maybe put the values in `responses.py` e.g.

```python
class SignatureHelpAvailalability:
  AVAILABLE = 'YES'
  NOT_AVAILABLE = 'NO'
  PENDING = 'PENDING'
```

optional.
___
*[ycmd/completers/language_server/language_server_completer.py, line 1071 at r2](https://reviewable.io/reviews/puremourning/ycmd-1/19#-Lr-vG1iCx4WZ1b4TFPM:-Lr-vG1iCx4WZ1b4TFPN:b6oyxwd) ([raw file](https://github.com/puremourning/ycmd-1/blob/2f29bd2cbbc6b990e5621390b761da088d9a6133/ycmd/completers/language_server/language_server_completer.py#L1071)):*
> ```Python
>   def SignatureHelpAvailable( self ):
>     if not self.ServerIsReady():
>       return 'PENDING'
> ```

i think we can return 'NO' early if self._signature_help_disabled is True

**Review by bstaletic — COMMENTED** [review]
For the API documentation mistakes, I was aware of those. I just couldn't get the web page to display correctly.
It's displaying correctly now.

> *[Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/19#-:-Lr-ylRf4Xr38XcP8n9a:bzh9m05)* status: 4 of 10 files reviewed, 5 unresolved discussions (waiting on @puremourning)

___
*[docs/openapi.yml, line 923 at r2](https://reviewable.io/reviews/puremourning/ycmd-1/19#-Lr-u_Ky2RZ2wPl7wG_4:-Lr-xnSU7lbTJM6qk1pq:bgpyyb4) ([raw file](https://github.com/puremourning/ycmd-1/blob/2f29bd2cbbc6b990e5621390b761da088d9a6133/docs/openapi.yml#L923)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

are we really accepting it in the body, rather than on the query string ? I thought the GET requests used the query string 
</blockquote></details>

Right. It's not in body. I just couldn't get the web page to display everything if I change it to `in: query`.

Done.
___
*[docs/openapi.yml, line 926 at r2](https://reviewable.io/reviews/puremourning/ycmd-1/19#-Lr-uXcn3YH71IMrtrn1:-Lr-y2lE1lAoEwxzl8g5:bqgoxp2) ([raw file](https://github.com/puremourning/ycmd-1/blob/2f29bd2cbbc6b990e5621390b761da088d9a6133/docs/openapi.yml#L926)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

> ```
>             The context data, including the current cursor position, and details
>             of dirty buffers.
> ```

Not sure this is accurate
</blockquote></details>

Copy/paste error... the "I'll get back to it" kind.
Done.
___
*[docs/openapi.yml, line 929 at r2](https://reviewable.io/reviews/puremourning/ycmd-1/19#-Lr-udaF5IBUdgLCyhBP:-Lr-yFpA8zFMi7SSZY-B:b380yuo) ([raw file](https://github.com/puremourning/ycmd-1/blob/2f29bd2cbbc6b990e5621390b761da088d9a6133/docs/openapi.yml#L929)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

pretty sure it isn't an object with subserver key, but subserver query parameter (at least it _was_)
</blockquote></details>

Yeah, I didn't change the query. Done.
___
*[ycmd/completers/completer.py, line 443 at r2](https://reviewable.io/reviews/puremourning/ycmd-1/19#-Lr-urOX7hNOnj9pTL6X:-Lr-ybYrDyx0DskLX2EP:bl7t8g3) ([raw file](https://github.com/puremourning/ycmd-1/blob/2f29bd2cbbc6b990e5621390b761da088d9a6133/ycmd/completers/completer.py#L443)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

maybe put the values in `responses.py` e.g.

```python
class SignatureHelpAvailalability:
  AVAILABLE = 'YES'
  NOT_AVAILABLE = 'NO'
  PENDING = 'PENDING'
```

optional.
</blockquote></details>

Sure, why not.
Done.
___
*[ycmd/completers/language_server/language_server_completer.py, line 1071 at r2](https://reviewable.io/reviews/puremourning/ycmd-1/19#-Lr-vG1iCx4WZ1b4TFPM:-Lr-yh-I1s_NGVoUC2xr:b-896fix) ([raw file](https://github.com/puremourning/ycmd-1/blob/2f29bd2cbbc6b990e5621390b761da088d9a6133/ycmd/completers/language_server/language_server_completer.py#L1071)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

i think we can return 'NO' early if self._signature_help_disabled is True
</blockquote></details>

Done.

**Review by puremourning — COMMENTED** [review]
Thanks, LGTM. Let's wait until we're happy with the client implementation then merge them together.

> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/19#-:-Lr0Hanh4i-_ZpEe6WiL:bbucm8p)* status: all files reviewed, 2 unresolved discussions (waiting on @puremourning)

**Review by puremourning — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/19#-:-Lr0Hiua1iYTtrWaKh-R:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @puremourning)

**Comment by puremourning** [comment]
just need to resolve conflicts then will merge

**Review by bstaletic — COMMENTED** [review]
Rebased and resolved.

> *[Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/19#-:-Lr1AB1Z7WwqO8B6CVns:b-kpk048)* status: 7 of 10 files reviewed, 2 unresolved discussions (waiting on @puremourning)

**Review by puremourning — APPROVED** [review]
looks good, but CI is red again :(

> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/19#-:-Lr4nyyGDSHPPgDI1aGF:blo89a2)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by bstaletic — COMMENTED** [review]
I think I fixed it, but wait for CI before merging.

> *[Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/19#-:-Lr4uCHf2V_77W4u8sBx:brrwg9j)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @puremourning)

**Review by bstaletic — COMMENTED** [review]
It works, the test failure is a flake.

> *[Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/19#-:-Lr57ZEA5IV4vaG2viUu:b-hgnozl)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @puremourning)

**Comment by puremourning** [comment]
will merge when conflicts resolved. thanks so much for this.

I am literally no closer to understanding these jedi unpicking errors, which has consumed nearly all of my time for 2 days :/

**Review by puremourning — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/19#-:-Lr9NZg5DTPfMLr4YieG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request closed without merging**
