### PR TITLE
[READY] GoToSymbol for C#

### PR DESCRIPTION
**Pull request by bstaletic**
This change is [Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/27)

### CODE REVIEW

**Review by puremourning — APPROVED** [review]
NICE!

Thanks!

Flake8 will moan about 2 blank lines i think but meh, that's way down the line.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/27#-:-MBEJ7SZDGuRIguAE6p-:b-ybeg5c)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by bstaletic — COMMENTED** [review]
Here are the flake8 errors:

```
/home/vsts/work/1/s/ycmd/completers/language_server/language_server_protocol.py:139:1: E302 expected 2 blank lines, found 1
/home/vsts/work/1/s/ycmd/completers/cs/cs_completer.py:602:44: YCM202 exactly one space required before )
/home/vsts/work/1/s/ycmd/tests/cs/subcommands_test.py:254:3: E124 closing bracket does not match visual indentation
/home/vsts/work/1/s/ycmd/tests/cs/subcommands_test.py:263:3: E124 closing bracket does not match visual indentation
```

> *[Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/27#-:-MBELF7r0JPbJSG35pq1:bynjqvh)* status: all files reviewed, 2 unresolved discussions

___
*[ycmd/completers/cs/cs_completer.py, line 610 at r1](https://reviewable.io/reviews/puremourning/ycmd-1/27#-MBELLSB2cKlfz7_Ochb:-MBELLSB2cKlfz7_Ochc:bxql8cn) ([raw file](https://github.com/puremourning/ycmd-1/blob/5203a3aecd36756eae094716215895dd49852f45/ycmd/completers/cs/cs_completer.py#L610)):*
> ```Python
>     response = self._GetResponse( '/findsymbols', request )
> 
>     if response[ 'QuickFixes' ]:
> ```

This whole block is taken from `_GoToReferences`. Maybe deduplicate?

Also `response[ 'QuickFixes' ]` could be "cached" instead of looked up twice.
___
*[ycmd/tests/cs/subcommands_test.py, line 257 at r1](https://reviewable.io/reviews/puremourning/ycmd-1/27#-MBELdXV7Jt3DslnKwPT:-MBELdXV7Jt3DslnKwPU:b-h8c2go) ([raw file](https://github.com/puremourning/ycmd-1/blob/5203a3aecd36756eae094716215895dd49852f45/ycmd/tests/cs/subcommands_test.py#L257)):*
> ```Python
>   ( 'DoSomething',
>     has_items(
>       LocationMatcher( PathToTestFile( 'testy', 'GotoTestCase.cs' ), 27, 8 ),
> ```

I'm using `has_items()` here because, if `Unicode.cs` gets visited, there will be a location in that file as well.

**Review by puremourning — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/27)* status: all files reviewed, 3 unresolved discussions (waiting on @bstaletic)

___
*[ycmd/completers/cs/cs_completer.py, line 619 at r1](https://reviewable.io/reviews/puremourning/ycmd-1/27#-MBFt8EP8t2XiPOTr-3q:-MBFt8EQ17w-dNVzbdRs:bzgrao) ([raw file](https://github.com/puremourning/ycmd-1/blob/5203a3aecd36756eae094716215895dd49852f45/ycmd/completers/cs/cs_completer.py#L619)):*
> ```Python
>             ref[ 'Line' ],
>             ref[ 'Column' ] ),
>           GetFileLines( request_data, ref[ 'FileName' ] )[ ref[ 'Line' ] - 1 ] )
> ```

if the file doesn't exist or the file path is unparseable, this will raise a key error ?

**Review by bstaletic — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/27)* status: all files reviewed, 3 unresolved discussions (waiting on @puremourning)

___
*[ycmd/completers/cs/cs_completer.py, line 619 at r1](https://reviewable.io/reviews/puremourning/ycmd-1/27#-MBFt8EP8t2XiPOTr-3q:-MBG2N3dEuT9gmkCQxHG:bpxtvv) ([raw file](https://github.com/puremourning/ycmd-1/blob/5203a3aecd36756eae094716215895dd49852f45/ycmd/completers/cs/cs_completer.py#L619)):*
<details><summary><i>Previously, puremourning (Ben Jackson) wrote…</i></summary><blockquote>

if the file doesn't exist or the file path is unparseable, this will raise a key error ?
</blockquote></details>

`GetFileLines` won't throw. It logs and swallows exceptions. We get a potentially empty list of file lines and pick only the `ref[ 'Line' ] - 1` index.

Am I missing anything?

**Comment by puremourning** [comment]
> Am I missing anything?

Won't the "line" - 1 index throw IndexError if the GetFileLines returns [] ?

**Review by bstaletic — COMMENTED** [review]
Ah, you're right. Though is this any more than a theoretical concern? Can it actually happen in practice? Roslyn had to have read the file and that happening followed by ycmd not being able to do it seems odd.

I guess "remount as readonly" is possible between receiving the response and trying to read the line.

> *[Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/27#-:-MBGEXNf-DONUUIMwbCR:b7036n9)* status: all files reviewed, 3 unresolved discussions (waiting on @puremourning)

**Comment by puremourning** [comment]
I know this happens a lot on the java server. Not sure how likely it is for roslyn.

**Review by bstaletic — COMMENTED** [review]
I fixed the flake8 errors too.

> *[Reviewable](https://reviewable.io/reviews/puremourning/ycmd-1/27#-:-MBHv5R5BLuJ1AkD0H8c:b-ganljr)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @puremourning)

___
*[ycmd/completers/cs/cs_completer.py, line 610 at r1](https://reviewable.io/reviews/puremourning/ycmd-1/27#-MBELLSB2cKlfz7_Ochb:-MBHtWYh9rPBnV_zmkx3:b-ecfuks) ([raw file](https://github.com/puremourning/ycmd-1/blob/5203a3aecd36756eae094716215895dd49852f45/ycmd/completers/cs/cs_completer.py#L610)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

This whole block is taken from `_GoToReferences`. Maybe deduplicate?

Also `response[ 'QuickFixes' ]` could be "cached" instead of looked up twice.
</blockquote></details>

It's not taken literally, after all.  This one does this dance to figure out the line of description.
___
*[ycmd/completers/cs/cs_completer.py, line 619 at r1](https://reviewable.io/reviews/puremourning/ycmd-1/27#-MBFt8EP8t2XiPOTr-3q:-MBHtgvsEfgi2PpLsTcN:b-896fix) ([raw file](https://github.com/puremourning/ycmd-1/blob/5203a3aecd36756eae094716215895dd49852f45/ycmd/completers/cs/cs_completer.py#L619)):*
<details><summary><i>Previously, bstaletic (Boris Staletic) wrote…</i></summary><blockquote>

`GetFileLines` won't throw. It logs and swallows exceptions. We get a potentially empty list of file lines and pick only the `ref[ 'Line' ] - 1` index.

Am I missing anything?
</blockquote></details>

Done.
___
*[ycmd/completers/cs/cs_completer.py, line 552 at r2](https://reviewable.io/reviews/puremourning/ycmd-1/27#-MBHux8fC9m4kyvqnW0U:-MBHux8fC9m4kyvqnW0V:bqqg4e9) ([raw file](https://github.com/puremourning/ycmd-1/blob/14ff3b06e6d692e71f5ef5937c155c9545f948e3/ycmd/completers/cs/cs_completer.py#L552)):*
> ```Python
> 
> 
>   def _GoToImplementation( self, request_data, fallback_to_declaration ):
> ```

All changes in this function were to avoid unnecessary lookups in dictionaries.
___
*[ycmd/completers/cs/cs_completer.py, line 648 at r2](https://reviewable.io/reviews/puremourning/ycmd-1/27#-MBHuenD6uPkvPHnSeAs:-MBHuenD6uPkvPHnSeAt:bqqg4e9) ([raw file](https://github.com/puremourning/ycmd-1/blob/14ff3b06e6d692e71f5ef5937c155c9545f948e3/ycmd/completers/cs/cs_completer.py#L648)):*
> ```Python
>       raise RuntimeError( 'No symbols found' )
> 
>   def _GoToReferences( self, request_data ):
> ```

All changes in this function were to avoid unnecessary lookups in dictionaries.
___
*[ycmd/completers/cs/cs_completer.py, line 874 at r2](https://reviewable.io/reviews/puremourning/ycmd-1/27#-MBHuZ0wBBw_hSbSR-GK:-MBHuZ0wBBw_hSbSR-GL:b-aws0o1) ([raw file](https://github.com/puremourning/ycmd-1/blob/14ff3b06e6d692e71f5ef5937c155c9545f948e3/ycmd/completers/cs/cs_completer.py#L874)):*
> ```Python
>     column_num = 1
>   contents = GetFileLines( request_data, filename )
>   line_num = max( len( contents ), line_num ) - 1
> ```

This is the same thing with the `IndexError`.

**Pull request merged**
